image: Visual Studio 2017
init:
  - git config --global core.autocrlf input
build_script:
  - cmd: build.cmd BuildPackage
test: off
version: 0.0.1.{build}
artifacts:
  - path: bin
    name: bin
  - path: temp
    name: nuget
nuget:
  account_feed: false
  project_feed: true
deploy:
  provider: NuGet
  #server:                  # remove to push to NuGet.org
  #api_key:
  #  secure: m49OJ7+Jdt9an3jPcTukHA==
  #skip_symbols: false
  #symbol_server:           # remove to push symbols to SymbolSource.org
  artifact: /temp/.*\.nupkg/
